### PR TITLE
feat: send messages to parent when running in the Electron app

### LINKED ISSUE #27: Split the repo into two parts
1. React App
2. Electron App, integrating React App as git submodule.

Goal: Run React App standalone on a webserver without Electron App.

### PR DESCRIPTION
**Pull request by krrprr**
This PR adds the functionality of sending a message to the parent window when running inside the electron app. This is needed in the following cases:
- copying text to the clipboard
- navigating to the `Connect to remote` screen via the `Disconnect` button (visible only when running in the electron)
- writing to the logs.

All this helps preserve the pre-split functionality of the XUD Explorer native application.

Currently, log files are not created when the app is accessed from the browser as it needs a separate solution.

Closes https://github.com/ExchangeUnion/xud-ui/issues/27

How to test:
in `xud-docker` dir

edit `images/proxy/src.py` by replacing the frontend branch `"main"` with `"feat/iframe"`

```bash
./tools/build proxy:latest
./tools/build utils:latest
```
If in feature branch
```bash
bash setup.sh --proxy.disabled=false --dev --use-local-images proxy
```
Set the IP:port in XUD Explorer's `Connect to remote` screen to `https://localhost:{port}` (the port is the usual proxy port 8889, 18889, 28889 depending on the network)

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Review by raladev — CHANGES_REQUESTED** [review]
- [ ] Try button; When i lost connection to proxy i got try page (and i cant move to main page from current state), but I was expecting an auto-connect page (second screen).
Screenshot from 2020-11-10 16-24-11
Screenshot from 2020-11-10 16-24-38

- [ ] right click button does not work in electron app :(

**Comment by raladev** [comment]
- [ ] Try button; When i lost connection to proxy i got try page (and i cant move to main page from current state), but i thought that but I was expecting an auto-connect page (second screen).
Screenshot from 2020-11-10 16-24-11
Screenshot from 2020-11-10 16-24-38

- [ ] right click button does not work in electron app :(

**Comment by krrprr** [comment]
> When i lost connection to proxy i got try page (and i cant move to main page from current state), but I was expecting an auto-connect page (second screen)

Thanks for noticing that! I completely missed that case. Fixed that now. (Also needs https://github.com/ExchangeUnion/xud-ui/pull/101)

> right click button does not work in electron app

Do you mean a menu does not open on right click? Afaik, his is a default behavior for electron and was like this before as well. I suggest we solve that later.

**Comment by raladev** [comment]
> Do you mean a menu does not open on right click? Afaik, his is a default behavior for electron and was like this before as well. I suggest we solve that later.

Oke, i will create separate issue for that.

**Review by raladev — APPROVED** [review]

**Pull request merged**
