### PR TITLE
feat: add trade view

### LINKED ISSUE #32: Trade view
Rename view Orderbook → Trade. Contains orderbook, graph, enter new order (market/limit), open orders.

### PR DESCRIPTION
**Pull request by krrprr**
Closes https://github.com/ExchangeUnion/xud-ui/issues/32

- [x] Order Book
- [x] Place Order
- [x] Open Orders

Also refactored the trade history in order to reuse the table. No expected changes in its behavior or design.

### CODE REVIEW

**Comment by krrprr** [comment]
To be implemented:
- [x] `total` field
- [x] warning dialog when the price is > +/-2% of the market price
- [x] filled % in the open orders
- [x] own orders highlighted in the order book

**Comment by raladev** [comment]
Notes after first look:


- we need to implement notifications as a next step - about matching/placing/filling/non-filling for markets. Otherwise these actions look non-friendly. I know nothing about my order after buy/sell button pressing, to check fill i need to go to trades tab, also i will not get info about non-successful fills, etc.

- [x] strange recalculation case for amount field (check video for steps); Not sure what happened, imo we should not recalculate amount field, it should be edited only by user for limit order. - https://gofile.io/d/wVfQzy
- [x] collateralization case is not handled in ui, i got `not enough funds` err and cant send place request to trigger collateralization -  for auto-extendable currencies we should not check max buy value of this currency;
- [ ] when I chose Market in order type combo box, I got strange number in the middle of orderbook, can u please explain what does it mean? If it is not a bug, would be good to think about better place for it (i assume that it is the price of order that will be executed, but im not sure) :)
[Screenshot](https://user-images.githubusercontent.com/29906866/105773458-fa975980-5f74-11eb-8164-3ca549c5c8ee.png)
- [ ] add left-padding for pair in combobox (ETH/BTC too close to thhe combobox border) like u do for limit/market combobox;
[Screenshot](https://user-images.githubusercontent.com/29906866/105771982-89ef3d80-5f72-11eb-9abb-e358ef7fa91e.png)
- [ ] if both sides are empty, display 1 message instead of 2 (order book is empty);
- [x] add `auto-extended` message for connext currencies as we did on wallet tab;
- [ ] would be good to remember chosen pair (save to local storage), opening first one is annoying because I need to check trade tab to understand was swap successful or not (because we have no notifications for now) and when i returning back i get  not my pair, but first one from combo box;
- [x] loader for order cancelling is required, sometimes orders are not disappear immediately, it took 1-1.5 sec.
- [x] - price changing leads to max available amount recalculation, but it is hard to notice and as a result it leads to misunderstanding.
Usually user set qty on first step (and on this step he checks his max available value) and price on second (like I did), but after price setting i got err because of too big qty (but im sure that i checked it before and it was fine). As a result i spent 10 mins in attempts to understand how it works - How to fix? I have no idea :( maybe add some animation for it and bigger description to hint.  
- [ ] would be good to add sorting to open orders table;
- [ ] when changing pair I get 3 different loaders - one for buy form, one for orderbook, one for opened orders tab. Can we just make one loader instead of three?

**Comment by krrprr** [comment]
Thanks for the feedback @raladev !

> imo we should not recalculate amount field, it should be edited only by user for limit order.

When the total is changed by the user, the amount **should** change accordingly. Tried to prevent the cases when the total changed due to the price change and that (the change of total) triggered the amount change but apparently there are still edge cases when this happens for some reason. I'll try to solve those as well but that's kind of tricky to tell the difference as there seem to be several rounds of `onChange` triggered.

> collateralization case is not handled in ui, i got not enough funds err and cant send place request to trigger collateralization - for auto-extendable currencies we should not check max buy value of this currency;

Can you help me understand what can be done in the UI trigger that?

> when I chose Market in order type combo box, I got strange number in the middle of order book, can u please explain what does it mean? If it is not a bug, would be good to think about better place for it (i assume that it is the price of order that will be executed, but im not sure) :)

It's the market price (when sell is selected then highest buy price in the order book and when buy is selected then the lowest sell price). It's also there when the limit is chosen. Maybe we can display it somehow differently to make it more understandable. Wouldn't change the location other that maybe just moving it to the right as the price is always located between buy and sell orders. Currently it does not indicate the price movement (up/down arrows like in CEXes) as we don't have a record for overall trade history. Currently the color is chosen according to whether the sell or buy order price is displayed. Maybe would make sense compare it to the last displayed price? The initial one would not have any data to be compared with, though. If volatility is low and the initial price would be there for minutes then it probably would not make sense.

> loader for order cancelling is required, sometimes orders are not disappear immediately, it took 1-1.5 sec.

It's actually implemented but the problem is that we alter list of data that is constantly being renewed and there's a delay because of that for some reason (noticed that normally the row disappears before the loader appears). Didn't want to spend too much time on this. May take another look later when higher priority issues are resolved.

> when changing pair I get 3 different loaders - one for buy form, one for orderbook, one for opened orders tab. Can we just make one loader instead of three?

I personally prefer to treat those blocks separately, so that if one of them, for some reason, is loading for longer time, others could already be displayed. And the loader of each block indicates that something's still loading while the other parts of the view can already be used.

> price changing leads to max available amount recalculation, but it is hard to notice and as a result it leads to misunderstanding.
> Usually user set qty on first step (and on this step he checks his max available value) and price on second (like I did), but after price setting i got err because of too big qty (but im sure that i checked it before and it was fine). As a result i spent 10 mins in attempts to understand how it works - How to fix? I have no idea :( maybe add some animation for it and bigger description to hint.

Agree. Thought the same but as I didn't have a solution either, I left it as is for now. I don't think a bigger description would solve this. Animation, maybe. Another idea: instead of the generic `Amount is larger than the max available amount` field error we could specify what exactly is causing this (sell limits / channel balance of X not sufficient OR not enough incoming capacity for Y).


No additional comments for other bullet points. Will fix those after the filled % is implemented.

**Comment by raladev** [comment]
> Can you help me understand what can be done in the UI trigger that?

How collateralization works?
Initially all connext channels have 0 Max buy tradinglimit. To increase it user should send placeorder request with qty and price and xud will send collateralization request to connext client. (Placeorder call returns `please wait for collateralization` message)
After collateralization user will get required Max buy limit for his order and he should place order again.

1. So, u just need to not block buy button if user tries to buy Connext currency and have enough another currency for that trade - sending placeorder request will trigger collateralization request sending.
2. if u got `collateralization` response, dont clean price/qty fields and display the text (with hint?) - better UX

>when sell is selected then highest buy price in the order book and when buy is selected then the lowest sell price

What if i use qty that bigger then qty of best bid/ask? Will the price be calculated correctly?

> It's also there when the limit is chosen.

It is not true. If u dont choose Market type, Order book does not contain this amount, but when u choose Market type and return Limit type back  it does not disappear - looks like a bug.

> Maybe we can display it somehow differently to make it more understandable.

IMO we can move it to not editable price field of  buy/sell form when Market type is selected + add hint on focus/click to non-editable field with price calculation description. (For Limit order this price is not required)

**Comment by krrprr** [comment]
> How collateralization works?

Yes, thank you for the explanation! I'll try to figure out something user friendly (maybe we could automatically place the order once the collateralization is done so that the user wouldn't have to do it twice?)

> It is not true. If u dont choose Market type, Order book does not contain this amount, but when u choose Market type and return Limit type back it does not disappear - looks like a bug.

I really could not reproduce this and this should not in any way be affected on whether the market or limit is chosen. So how exactly did it happen?

> What if i use qty that bigger then qty of best bid/ask? Will the price be calculated correctly?

The number in the middle of order book is only affected by:
1. buy or sell selected by the user;
2. the best bid / ask in order book.

Market/limit nor the price the user has typed in should have no effect on this. It does not show nor calculate the (estimate) price for market orders. Just indicates the current market situation for reference.

> IMO we can move it to not editable price field of buy/sell form when Market type is selected + add hint on focus/click to non-editable field with price calculation description. (For Limit order this price is not required)

Would not vote for this as it's not reliable. The data could change either right before or during placing the order and the final price can therefore be different from the one displayed. For instance, Binance also displays just `Market` in the price field (like we do) when market order is selected and does no calculations for this.

**Comment by krrprr** [comment]
Also, do we need to display the trading pair in the open orders' table? It's currently same for every row. Or did I get it wrong and we want to show all open trades, not only for the selected trading pair?

**Comment by krrprr** [comment]
> would be good to add sorting to open orders table;

just thinking it would make sense to also add an option to sort by `createdAt` but I wouldn't add this column in the table. The table has lots of columns already and we already have a problem fitting it into smaller screens. And imo this info does not add very much value. Would it make sense to add the sorting option without displaying the time order was created? Opinions?

**Comment by krrprr** [comment]
Although there was an idea to display an order in `open orders` for some seconds after it has been completely filled, I did not find any way to do this as we cannot tell what was the initial order amount based on trade history, thus we cannot compare the quantity of trades for an order to find out if it's 100% filled when it does not show up in `listtrades` (we cannot be sure if the order was filled or cancelled).
If there is data which I'm not aware of, I'd gladly implement this functionality.

**Comment by krrprr** [comment]
@raladev @kilrau @peartobear any thoughts on my previous 3 comments/questions?

**Comment by krrprr** [comment]
I removed the highlighting of own orders as I discovered the `listorders` sometimes returns a rounded quantity. It's not concise and probably some javascript number issue on the xud side. The quantity in `orderbook` response remains as it was inserted by the user. That means we do not have a reliable way to tell if a row in the order book contains own order since we are arbitrarily getting false negatives for that equation.

**Comment by kilrau** [comment]
> I really could not reproduce this and this should not in any way be affected on whether the market or limit is chosen. So how exactly did it happen?

@raladev 

> Market/limit nor the price the user has typed in should have no effect on this. It does not show nor calculate the (estimate) price for market orders. Just indicates the current market situation for reference.

Agreed, this number should be sth like the current mid market price and not be affected by anything the user "is about to do".

> Would not vote for this as it's not reliable. The data could change either right before or during placing the order and the final price can therefore be different from the one displayed. For instance, Binance also displays just `Market` in the price field (like we do) when market order is selected and does no calculations for this.

:+1: 


> Also, do we need to display the trading pair in the open orders' table? It's currently same for every row. Or did I get it wrong and we want to show all open trades, not only for the selected trading pair?

We want to show all open trades, not only for the selected pair. That's how Binance "Advanced view" does it too.

> just thinking it would make sense to also add an option to sort by createdAt but I wouldn't add this column in the table. The table has lots of columns already and we already have a problem fitting it into smaller screens. And imo this info does not add very much value. Would it make sense to add the sorting option without displaying the time order was created? Opinions?

Wouldn't do any of this, most ppl won't have tons of orders open, this is an optimization we can do after initial user feedback.

> I removed the highlighting of own orders as I discovered the `listorders` sometimes returns a rounded quantity. It's not concise and probably some javascript number issue on the xud side. The quantity in `orderbook` response remains as it was inserted by the user. That means we do not have a reliable way to tell if a row in the order book contains own order since we are arbitrarily getting false negatives for that equation.

Wait - that needs to be fixed. Shouldn't it be if own order price == orderbook price point then display own order visual mark?

**Comment by krrprr** [comment]
> Wouldn't do any of this, most ppl won't have tons of orders open, this is an optimization we can do after initial user feedback.

Do you mean no sorting at all right now? Or just no sorting by `createdAt`?

> Wait - that needs to be fixed. Shouldn't it be if own order price == orderbook price point then display own order visual mark?

It should but currently it does not add up in some cases since the xud may return some incorrect data for `listorders`. We'd first have to fix it on the xud side and then enable the highlighting again.

@kilrau

**Comment by kilrau** [comment]
> Do you mean no sorting at all right now? Or just no sorting by `createdAt`?

No sorting at all needed rn

> It should but currently it does not add up in some cases since the xud may return some incorrect data for listorders. We'd first have to fix it on the xud side and then enable the highlighting again.

Alright, agreed. Could you open an issue on xud side for that?

**Comment by krrprr** [comment]
> Alright, agreed. Could you open an issue on xud side for that?

https://github.com/ExchangeUnion/xud/issues/2062

**Review by ghost — APPROVED** [review]

**Review by raladev — APPROVED** [review]

**Pull request merged**
